# Generated by Django 6.0.3 on 2026-04-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactiondata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=70)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
    ]
