# Generated by Django 6.0.3 on 2026-04-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondata',
            name='filt',
            field=models.BooleanField(default=True),
        ),
    ]
